### ISSUE TITLE
NameError: name 'zlad' is not defined

### ISSUE THREAD

**Issue by surakeshpt** [stefanfluck/palmpy#52]
I installed the palmpy but while executing the make_static.py it shows an error as shown below.

START CREATING DOMAIN 0
Origin before cutting: 682917.4999999999/247513.50000000105. Resolution: 0.5000000000002621 m.
Origin after cutting: 682924.9999999999/247288.00000000093. Resolution: 4.0 m.
Raster Size: X: 192 Y: 192
Shifted the input array downwards by 404.31 meters.
Traceback (most recent call last):

  File "/home/thirurrp/Downloads/palmpy-master/examples/tutorial_example/make_static.py", line 604, in <module>
    for m in range(len(zlad)):

NameError: name 'zlad' is not defined

**Comment by stefanfluck** [comment]
Hi Rakesh, if you feel the issue is solved as discussed in the email, please close the ticket 😊. Kind wishes, Stefan

**Comment by surakeshpt** [comment]
it solved as there was an wrong entry in the .ini file
